import Head from "next/head";

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-8 px-12 m-0 min-h-screen">
        <h1 className="text-4xl pl-99">ひらまのホームページ</h1>
        <h1 className="mt-8 text-2xl font-semibold">プロフィール</h1>

        <h2>プロフィール</h2>
        <ul>
          <li>2000年9月13日生まれ</li>
          <li>おとめ座</li>
          <li>趣味はバイクでツーリング</li>
        </ul>
        <h1 className="mt-8 text-2xl font-semibold">オロロンラインでの一枚</h1>
        <div>
          <img src="IMG_5905.jpg" alt="オロロンラインとバイク" />
          <div className="p-4 md:p-5">
            <h2 className="text-lg font-bold text-gray-800 underline"></h2>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
